// Exercise 1.9. Each of the following two procedures defines a method for adding two
// positive integers in terms of the procedures inc, which increments its argument by 1,
// and dec, which decrements its argument by 1.

// Definition 1: recursive process
export const addRecursive = (a: number, b: number): number => {
    if (a === 0) return b;
    return inc(addRecursive(dec(a), b));
};

// Definition 2: iterative process
export const addIterative = (a: number, b: number): number => {
    if (a === 0) return b;
    return addIterative(dec(a), inc(b));
};

// Helper functions
export const inc = (x: number): number => x + 1;
export const dec = (x: number): number => x - 1;

// Using the substitution model, illustrate the process generated by each procedure in evaluating (+ 4 5). Are these processes iterative or recursive?
//
// -----------------------------------------------------------
//
// Definition 1 expanded by the applicative substitution model
//
// addRecursive(4, 5)
// inc(addRecursive(3, 5))
// inc(inc(addRecursive(2, 5)))
// inc(inc(inc(addRecursive(1, 5))))
// inc(inc(inc(inc(addRecursive(0, 5)))))
// inc(inc(inc(inc(5))))
// inc(inc(inc(6)))
// inc(inc(7))
// inc(8)
// 9
//
// We clearly see by the shape of the process that it is linear recursive process
//
// Definition 2 is expanded like this
//
// addIterative(4, 5)
// addIterative(3, 6)
// addIterative(2, 7)
// addIterative(1, 8)
// addIterative(0, 9)
// 9
//
// Obviously, it is linear iteration in place here.